### ISSUE TITLE
Conflicts with windows not being case sensitive

### ISSUE THREAD

**Issue by picstart** [JChristensen/Timezone#14] opened 2017-04-07 18:36 UTC
The code has a  dependency on Time.h .
Unpleasantly there is also a time.h embedded in the Arduino IDE
This unfortunate issue of two files that are considered identical by Windows results in time.h being used and the many compile errors produced make the troubleshooting frustrating. The work around is to rename Time.h to something like MyTime.h and then chase down the includes within includes within includes to replace all references to Time.h and Time.cpp with MyTime.h and MyTime.h

**Comment by per1234** [comment] 2017-04-07 21:24
Duplicate of https://github.com/JChristensen/Timezone/issues/7.

Would be solved by merging https://github.com/JChristensen/Timezone/pull/8.

**Closed** 2018-01-09 01:49 UTC
